# PHP

phpfpm-gitscrum:
  image: yewill/docker-gitscrum
  restart: always
  environment:
    - DEBUG=1
  volumes:
    - ./config/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./config/php.ini:/usr/local/etc/php/php.ini
    - ./www:/var/www/html
    - ./log/php-fpm:/var/log/php-fpm
  links:
    - mysql-gitscrum

# NGINX
nginx-gitscrum:
  restart: always
  image: nginx
  ports:
    - "80:80"
  links:
    - phpfpm-gitscrum
  volumes:
    - ./config/server.conf:/etc/nginx/conf.d/default.conf
    - ./www:/var/www/html
    - ./log/nginx:/var/log/nginx

# MYSQL
mysql-gitscrum:
  restart: always
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: gitscrum
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: develop
  volumes:
    - ./mysql/databases:/var/lib/mysql
    - ./log/mysql:/var/log/mysql
